minecord.error.discord_bad_data=Discord sent bad data, please try again later
minecord.error.discord_only=This command can only be run in Discord
minecord.error.invalid_attachment=`{0}` must be an attachment but no attachment was sent
minecord.error.invalid_boolean=`{0}` must be a true or false but was `{1}`
minecord.error.invalid_channel=`{0}` must be a Discord channel but was `{1}`
minecord.error.invalid_double=`{0}` must be a number but was `{1}`
minecord.error.invalid_long=`{0}` must be an integer but was `{1}`
minecord.error.invalid_mentionable=`{0}` must be a Discord user, channel, or role but was `{1}`
minecord.error.invalid_role=`{0}` must be a Discord role but was `{1}`
minecord.error.invalid_user=`{0}` must be a Discord user but was `{1}`
minecord.error.no_required_option=Missing required option `{0}`
minecord.error.no_subcommand=Subcommand must be one of: {0}
minecord.error.no_subcommand_for_group=Subcommand for group {0} must be one of: {1}
minecord.error.no_subcommand_group=Subcommand group must be one of: {0}
minecord.error.no_subcommand_group_or_subcommand=Subcommand group or subcommand must be one of: {0}
minecord.generic.false=False
minecord.generic.true=True