codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "0...100"
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false

ignore:
  - src/main/java/br/**/*
