# Version catalog is a central place for you to declare and version dependencies
# https://docs.gradle.org/current/userguide/platforms.html#sub:version-catalog
# https://docs.gradle.org/current/userguide/platforms.html#sub::toml-dependencies-format

[versions]
# build
shadow = "9.6.1"
# runtime
kotlin = "2.4.10"
kotlinxCoroutines = "1.11.0"
argparser = "2.0.7"
# test
kotest = "6.2.4"

[libraries]
kotlinGradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinxCoroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
argparser = { module = "com.xenomachina:kotlin-argparser", version.ref = "argparser" }
kotestAssertions = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotestFramework = { module = "io.kotest:kotest-framework-engine", version.ref = "kotest" }
kotestRunner = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }

[bundles]
kotest = ["kotestAssertions", "kotestFramework", "kotestRunner"]

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
kotest = { id = "io.kotest", version.ref = "kotest" }
