# Version catalog is a central place for you to declare and version dependencies
# https://docs.gradle.org/current/userguide/platforms.html#sub:version-catalog
# https://docs.gradle.org/current/userguide/platforms.html#sub::toml-dependencies-format

[versions]
minecord = "0.19.0"
# build
shadow = "9.6.1"
# runtime
kotlin = "2.4.10"
kotlinxCoroutines = "1.11.0"
logback = "1.6.3"
jda = "6.6.0"
jda-ktx = "0.15.0"
argparser = "2.0.7"
# test
kotest = "6.2.4"

[libraries]
kotlinGradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinxCoroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
jda = { module = "net.dv8tion:JDA", version.ref = "jda" }
jdaKtx = { module = "club.minnced:jda-ktx", version.ref = "jda-ktx" }
argparser = { module = "com.xenomachina:kotlin-argparser", version.ref = "argparser" }
kotestAssertions = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotestFramework = { module = "io.kotest:kotest-framework-engine", version.ref = "kotest" }
kotestRunner = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }

[bundles]
jda = ["jda", "jdaKtx"]
kotest = ["kotestAssertions", "kotestFramework", "kotestRunner"]

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
kotest = { id = "io.kotest", version.ref = "kotest" }
