package com.tisawesomeness.minecord.database.dao;

/**
 * Represents something that can be banned from using the bot.
 */
public interface Bannable extends DbObject {
    /**
     * Whether this is banned.
     */
    boolean isBanned();

    // Generated by lombok
    Bannable withBanned(boolean banned);
}
