package com.tisawesomeness.minecord.database;

import com.tisawesomeness.minecord.Lang;

import java.sql.SQLException;
import java.util.Optional;

/**
 * An object containing values for each {@link com.tisawesomeness.minecord.setting.DMSetting}.
 */
public interface DMSettingContainer {
    // Methods in subclass generated by lombok
    long getId();
    boolean isBanned();

    // Methods in subclass generated by lombok
    Optional<String> getPrefix();
    DMSettingContainer withPrefix(Optional<String> prefix);
    Optional<Lang> getLang();
    DMSettingContainer withLang(Optional<Lang> lang);

    /**
     * Updates or inserts this object into the database.
     * @throws SQLException If a database error occurs
     */
    void update() throws SQLException;
}
