package com.tisawesomeness.minecord.database;

import com.tisawesomeness.minecord.Lang;

import java.util.Optional;

/**
 * An object containing values for each {@link com.tisawesomeness.minecord.setting.DMSetting}.
 */
public interface DMSettingContainer extends DbObject {
    // Methods in subclass generated by lombok
    Optional<String> getPrefix();
    DMSettingContainer withPrefix(Optional<String> prefix);
    Optional<Lang> getLang();
    DMSettingContainer withLang(Optional<Lang> lang);
}
